### ISSUE TITLE
Semver DOS moderate vulnerability

### ISSUE THREAD

**Issue by marina-mosti** [bugsnag/bugsnag-source-maps#85]
### Describe the bug

<img width="540" alt="image" src="https://github.com/bugsnag/bugsnag-source-maps/assets/14843771/f8322613-3599-4df6-a7e7-6304d2ebcded">

The `read-pkg-up` version used for this lib has a deep dep that has currently a moderate warning for possible DOS.
Any chance you can update it? :) The latest versions use `read-pkg` 5+ which seems to have a more recent version without the issue

### Steps to reproduce
`yarn audit` 

### Environment
* bugsnag-source-maps version:
* Uploading for:
	* [ ] Browser
	* [ ] Node
		* Node version:
	* [ ] React Native
		* React Native version:
* Command that was run:

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

### Example code snippet 

```
# (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by mclack** [comment]
Hi @marina-mosti 

So far I've been unable to reproduce this vulnerability report.

Can you please confirm what version of `yarn` you were using when you performed this `yarn audit`?  Any other additional reproduction steps you can provide would be useful for us to know in order to reproduce and investigate this.

**Comment by marina-mosti** [comment]
Hey @mclack thanks for the reply, yeah I'm not entirely sure what `yarn audit` is doing internally but I just ran it directly on your codebase and it definitely doesn't show up. However, if you run `npm audit` you can see it:

<img width="731" alt="image" src="https://github.com/bugsnag/bugsnag-source-maps/assets/14843771/b90a7bd6-626b-4271-bd6d-3d434898bc00">

**Comment by mclack** [comment]
Hi @marina-mosti 

After investigating this some more, the vulnerability seems to come from a dependency of a dev dependency (Jest). This means that it won’t get installed or used when installing the source-maps package using npm install @bugsnag/source-maps.

I imagine you’re seeing this by cloning our repo and installing all of the dependencies including the dev dependencies, which wouldn’t usually get installed.

As this is not a vulnerability that should be affecting any users using the library, this probably isn’t something we’ll be able to update too soon. However, it is on our radar that there are some dependencies we want to fix.

I hope that all makes sense. Please let us know if you have any other questions, otherwise we will close this issue out for the time being.

**Comment by marina-mosti** [comment]
Hi @mclack. Thanks so much for taking the time to investigate, I'm truly surprised at false positive from `yarn audit` and the gap between reports between it and the npm audit tools.
