### ISSUE TITLE
"form-data" library is dead, use native FormData

### ISSUE THREAD

**Issue by attenzione** [bugsnag/bugsnag-source-maps#97]
### Describe the bug
`form-data` library is old, [abandoned](https://github.com/form-data/form-data/issues/544) and has [deprecation warning](https://github.com/form-data/form-data/issues/563) with Node 21.

### Environment
* bugsnag-source-maps version: 2.0.0
* Uploading for:
	* [ ] Node
		* Node version: 21.8.0
* Command that was run: webpack build

**Comment by mclack** [comment]
Hi @attenzione 

Thanks for bringing this to our attention.

You mention that you used the `webpack build` command - does this mean that you are using our [Webpack plugin](https://docs.bugsnag.com/build-integrations/webpack/), or are you using `bugsnag-source-maps` directly? Generally we would recommend trying to use the [BugSnag CLI](https://docs.bugsnag.com/build-integrations/bugsnag-cli/) for source map uploads if you can, as we have made a lot of improvements to this recently, and are moving towards this being the primary recommended tool for source map uploads.

If you are using our Webpack plugin, then this does still currently use `bugsnag-source-maps` as a dependency, but eventually this will be updated to seamlessly use the CLI instead. We don't have an exact ETA for this work yet, but if you are using the Webpack plugin and would like to be kept updated on this, then we would be happy to do so.

Please let us know if you have any questions about this, otherwise our recommendation would be to try and switch to using the [BugSnag CLI](https://docs.bugsnag.com/build-integrations/bugsnag-cli/) for your source maps if you start using a Node version where `form-data` is fully deprecated.

**Comment by attenzione** [comment]
Hi @mclack,

Thanks for the quick response. 

I’m currently using the plugin only for source maps upload and hadn't looked into the CLI version before. I’ll give the CLI version a try and get back to you with comments in about a week.

**Comment by mclack** [comment]
Hi @attenzione 

As there hasn't been any activity here in a while, we are now going to close this issue. I see [you mentioned this](https://github.com/bugsnag/bugsnag-cli/issues/108#issuecomment-2377003541) when you were trying to migrate to `bugsnag-cli`, but had issues using `yarn`, and this should now be resolved.

If you do have any further questions or problems, then you may prefer to open a ticket with us directly by contacting support@bugsnag.com, and we will be happy to assist you further.

**Comment by attenzione** [comment]
Hi @mclack,
 
Thanks for the update. I'll definitely migrate to `bugsnag-cli`.

**Comment by ljharb** [comment]
> form-data library is old, https://github.com/form-data/form-data/issues/544 and has https://github.com/form-data/form-data/issues/563 with Node 21.

fwiw, none of these remain true (except "old", i guess?)
